Delete module for today before building
GeoscienceAustralia/dea-airflow pull request #238
Opened 2021-03-22 04:24 UTC by kieranricardo

This PR deletes the module with todays date before attempting to build the module.

For some reason my recent build didn't use the latest `dea-cogger` from https://packages.dea.ga.gov.au/dea-cogger/ so I'm re-building the module.

2021-03-22 04:27 UTC, omad commented on dags/nci_build_dea_module.py
> +        rm -r /g/data/v10/public/modules/dea/{datetime.datetime.now().strftime("%Y%m%d")}
Can you change it to use the shell to get the current day, I suspect that python code here will run in UTC and delete yesterdays module (or fail) if run before 10 or 11 in the AM.
`$(date +%Y%m%d)`

2021-03-22 04:37 UTC, kieranricardo commented on dags/nci_build_dea_module.py
> +        rm -r /g/data/v10/public/modules/dea/{datetime.datetime.now().strftime("%Y%m%d")}
This is how `dea-orchestration` gets the date:  **https://github.com/GeoscienceAustralia/dea-orchestration/blob/19ed1ca001dd5fbb692ba4921d9552d3973fbae1/nci_environment/build_environment_module.py#L102**

I think we should probably use the same method to make sure we're deleting the same module we're building, what do you reckon?

2021-03-25 00:25 UTC, omad requested changes

2021-03-25 00:29 UTC, kieranricardo commented
good point! I'll check the timezone

2021-03-25 00:37 UTC, kieranricardo commented
you were right! The NCI uses AESDT, I'll this in

2021-03-25 01:50 UTC, omad approved these changes
Awesome!

Sorry I forgot to press *submit* on the review on Monday! :(

2021-03-25 01:50 UTC, merged