Bulk Indexing for S2 NRT into Sandbox Database
GeoscienceAustralia/dea-airflow pull request #255
Opened 2021-04-01 04:37 UTC by kieranricardo

2021-04-01 05:07 UTC, pindge commented
No, u cannot do that for NRT

2021-04-01 05:09 UTC, pindge requested changes

2021-04-01 05:09 UTC, pindge commented on dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing_sandbox.py
> +        Secret("env", "DB_USERNAME", SECRET_ODC_WRITER_NAME, "postgres-username"),
also sandbox db has a different user

2021-04-01 05:09 UTC, pindge commented on dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing_sandbox.py
> +    URI = f"s3://dea-public-data/L2/sentinel-2-nrt/S2MSIARD/{uri_date}/**/ARD-METADATA.yaml"
u should watch my video.

2021-04-13 03:15 UTC, kieranricardo commented on dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing_sandbox.py
> +        Secret("env", "DB_USERNAME", SECRET_ODC_WRITER_NAME, "postgres-username"),
just tested and `sandbox` has a user w/ the same name and password so I think this works

2021-04-13 03:17 UTC, kieranricardo commented
@pindge I just checked and `sandbox` DB does have the `eo_plus` metadata type, so I think this DAG will actually work

2021-04-13 04:58 UTC, pindge requested changes

2021-04-13 04:58 UTC, pindge commented on dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing_sandbox.py
> +from infra.podconfig import NODE_AFFINITY
This has been changed to `ONDEMAND_NODE_AFFINITY`

2021-04-13 04:58 UTC, pindge commented on dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing_sandbox.py
> +    "owner": "Pin Jin",
Change this please

2021-04-13 05:56 UTC, kieranricardo commented on dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing_sandbox.py
> +    "owner": "Pin Jin",
whoops sorry! didn't mean to shove the blame onto you

2021-04-14 02:08 UTC, pindge requested changes

2021-04-14 02:08 UTC, pindge commented on dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing_sandbox.py
> +    SECRET_ODC_WRITER_NAME,
no this one wont work.

2021-04-14 02:08 UTC, pindge commented on dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing_sandbox.py
> +        Secret("env", "DB_USERNAME", SECRET_ODC_WRITER_NAME, "postgres-username"),
create a sandbox db secret in infra variables

```
Variables.get('sandbox-db-writter-secret', 'ows-db')

2021-04-14 02:10 UTC, pindge approved these changes

2021-04-14 02:10 UTC, pindge commented on dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing_sandbox.py
> +        "DB_DATABASE": "sandbox",
move this down to secret, 

for example
```
 Secret("env", "DB_PASSWORD", "odc-writer", "postgres-password"),
```

2021-04-18 23:46 UTC, kieranricardo commented
@pindge I think I fixed all the things we talked about, can you have another look please?

2021-04-22 03:17 UTC, pindge commented
> @pindge I think I fixed all the things we talked about, can you have another look please?

can u fix the conflict?

2021-07-14 05:48 UTC, closed without merging