Update the ARD sync to include GQA as a message attribute
GeoscienceAustralia/dea-airflow pull request #267
Opened 2021-04-14 05:38 UTC by alexgleith

* Update the message attribute to include GQA
* Fix the STAC upload to set the mimetype properly

2021-04-14 05:42 UTC, alexgleith commented
Sorry about all the formatting changes. The git commit hook made me do it.

2021-04-14 05:43 UTC, omad submitted a review, later dismissed
Looks good to me!

2021-04-15 03:02 UTC, omad requested changes
Hooray for tests!! ✨🎆

I've got most of the structure in place in the `develop` branch for running them in CI. It should be easy to move into `master` and merge with this one too.

2021-04-15 03:20 UTC, alexgleith commented on scripts/c3_to_s3_rolling.py
> +                content_type="text/vnd.yaml",
I read the official (lol) source here: https://stackoverflow.com/questions/332129/yaml-media-type

Key point:
>On Chrome application/yaml will download, while text/yaml will display.

And the answer I listened to: https://stackoverflow.com/a/38000954/2002176

Hang on and I'll test.

2021-04-15 03:26 UTC, alexgleith commented on scripts/c3_to_s3_rolling.py
> +                content_type="text/vnd.yaml",
application/yaml: https://dea-public-data-dev.s3-ap-southeast-2.amazonaws.com/test/app-yaml.yaml
text/vnd.yaml: https://dea-public-data-dev.s3-ap-southeast-2.amazonaws.com/test/vnd-yaml.yaml

2021-04-15 03:27 UTC, alexgleith commented on scripts/c3_to_s3_rolling.py
> +    command = f"aws s3 sync {local_path} {s3_path} --only-show-errors --delete --exclude {excludes}"
Wait, I think mine is wrong now.

2021-04-15 03:32 UTC, alexgleith commented on tests/test_c3_to_s3_rolling.py
> +    with open(local_stac, "r") as f:
Nah, the string is pushed to S3 the encoded version is hashed.

2021-04-15 04:40 UTC, omad commented on scripts/c3_to_s3_rolling.py
> +                content_type="text/vnd.yaml",
Firefox downloads both of those. I'm happy with anything (since there's no standard) so long as we get the behaviour we want in the applications we care about. :)

2021-04-15 04:45 UTC, omad commented on tests/test_c3_to_s3_rolling.py
> +    with open(local_stac, "r") as f:
Inside this test, we only care about the `bytes` variable. And we don't need to mess around with `write()` and `seek()` to get it.

2021-04-15 04:47 UTC, omad commented on tests/test_c3_to_s3_rolling.py
> +        )
```suggestion
    content = None
    with open(local_stac, "rb") as f:
        stac_content = f.read()

        upload_s3_resource(
            bucket_name,
            key_json,
            stac_content,
            content_type="application/json",
        )

        upload_s3_resource(
            bucket_name,
            key_txt,
            stac_content,
        )
```

2021-04-15 04:52 UTC, alexgleith commented on tests/test_c3_to_s3_rolling.py
> +    with open(local_stac, "r") as f:
Ok ok, simplified.

2021-04-15 04:58 UTC, omad commented on tests/test_c3_to_s3_rolling.py
> +        content = f.read()
boto3 does still want `bytes` not `str` I think, and this will read a `str`. Try:
```suggestion
    content = local_stac.read_bytes()
```

2021-04-15 05:02 UTC, alexgleith commented on tests/test_c3_to_s3_rolling.py
> +        content = f.read()
Nah, the test works which means boto works.

2021-04-15 05:11 UTC, omad approved these changes
🎉✨

2021-04-15 05:57 UTC, merged