Automated reporting
GeoscienceAustralia/dea-airflow pull request #400
Opened 2021-07-08 06:03 UTC by tmcadam

2021-07-09 03:08 UTC, pindge submitted a review, later dismissed

2021-07-12 00:08 UTC, tmcadam commented
@pindge I think is ready to merge to master. Could you please review again.

2021-07-12 03:08 UTC, pindge requested changes

2021-07-12 03:08 UTC, pindge commented on dags/infra/variables.py
> +S2_NRT_AWS_CREDS = "wagl-nrt-aws-creds"
Is this related to your dags? IT looks likes it related to WAGL

2021-07-12 03:08 UTC, pindge commented on dags/infra/connections.py
> +DB_REP_WRITER_CONN_DEV = "db_rep_writer_dev"
is this created in Terraform? if not, do not put it here

2021-07-12 03:10 UTC, tmcadam commented on dags/infra/connections.py
> +DB_REP_WRITER_CONN_DEV = "db_rep_writer_dev"
No. Can it be added to Terraform?

2021-07-12 03:11 UTC, pindge commented on dags/infra/connections.py
> +DB_REP_WRITER_CONN_DEV = "db_rep_writer_dev"
did you create this via airflow connection UI?

2021-07-13 02:34 UTC, tmcadam commented on dags/infra/variables.py
> +S2_NRT_AWS_CREDS = "wagl-nrt-aws-creds"
No , not related to my dags. I'll take it out, might have got this by mistake when merging commits from develop.

2021-07-13 02:34 UTC, tmcadam commented on dags/infra/connections.py
> +DB_REP_WRITER_CONN_DEV = "db_rep_writer_dev"
Yes, created it in sandbox UI

2021-07-13 02:46 UTC, pindge commented on dags/infra/connections.py
> +DB_REP_WRITER_CONN_DEV = "db_rep_writer_dev"
Happy for you to create a `connections.py` within your project, but this isnt the right place for it.

2021-07-13 03:25 UTC, tmcadam commented on dags/infra/connections.py
> +DB_REP_WRITER_CONN_DEV = "db_rep_writer_dev"
Okay, I'll move  these into our folder?
```
DB_REP_WRITER_CONN_DEV = "db_rep_writer_dev"
DB_REP_WRITER_CONN_PROD = "db_rep_writer_prod"
S3_REP_CONN = "s3_bucket_rep"
```
and the variable 
`COP_API_REP_CREDS = "copernicus_api_password"
`

2021-07-13 03:32 UTC, pindge commented on dags/infra/connections.py
> +DB_REP_WRITER_CONN_DEV = "db_rep_writer_dev"
yes

2021-07-13 04:22 UTC, pindge approved these changes

2021-07-13 04:22 UTC, pindge commented
LGTM

2021-07-13 04:25 UTC, merged