Add sentinel_2_nrt indexing package
GeoscienceAustralia/dea-airflow pull request #61
Opened 2020-09-01 23:59 UTC by pindge

- read variable configuration from airflow variable setting
- utility tool for ad-hoc execution
   - ows-update-ranges
   - cubedash-gen
- archiving process 
- pending discussion then add indexing process

2020-09-02 02:41 UTC, alexgleith commented
What's the justification for splitting this out into so many files?

2020-09-02 02:52 UTC, pindge commented
> What's the justification for splitting this out into so many files?

I am splitting archiving process and indexing process. `ows-update --views` takes forever to run, indexing should run by itself.

`ows-update --views` and `cube-dash gen` via subdag operator have a ad-hoc dag by itself, where by passing `{{ dag_run.conf.products }}` it can update products as defined, so we don't have to `kubectl exec -it pod bash` to run updates as needed.

because it is split into multiple parts, it makes sense to share a common config file and common image constant file.

![indexing-Page-2](https://user-images.githubusercontent.com/24644475/91926426-94d2d880-ed1a-11ea-99e0-01e4c19a3a63.png)

2020-09-04 03:12 UTC, NikitaGandhi requested changes

2020-09-04 03:12 UTC, NikitaGandhi commented on dags/env_var/infra.py
> +DB_HOSTNAME = Variable.get("db_hostname", "db-writer")
please revise above config as per this to be consistent: https://bitbucket.org/geoscienceaustralia/datakube/pull-requests/807/fix-indexing-endpoint-and-deploy-sandbox/diff

2020-09-04 04:04 UTC, omad submitted a review, later dismissed
Nothing urgent, looks okay so long as it works and I haven't tested that. :)

2020-09-04 04:04 UTC, omad commented on dags/sentinel_2_nrt/utility_explorer_summary.py
> +    START = DummyOperator(task_id="start_explorer_refresh_stats")
We don't need these START/END markers, and they slow things down. I feel guilty for starting the practice. I think in some cases they make things clearer, but they're really not necessary.

2020-09-04 04:49 UTC, pindge commented on dags/sentinel_2_nrt/utility_explorer_summary.py
> +    "email_on_failure": False,
ok, so maybe not for utility ones,  those are only to be used when manual runs are required. I will set true for the processing ones

2020-09-04 04:49 UTC, pindge commented on dags/sentinel_2_nrt/utility_explorer_summary.py
> +    START = DummyOperator(task_id="start_explorer_refresh_stats")
will remove

2020-09-04 04:50 UTC, pindge commented on dags/sentinel_2_nrt/sentinel_2_nrt_archive.py
> +    OWS_UPDATE_EXTENTS = SubDagOperator(
I need to find out how to make it a function call, as I kind grabbed this from airflow example from github

2020-09-04 04:50 UTC, pindge commented on dags/env_var/infra.py
> +DB_HOSTNAME = Variable.get("db_hostname", "db-writer")
Fixed

2020-09-04 05:08 UTC, NikitaGandhi approved these changes

2020-09-04 05:17 UTC, NikitaGandhi approved these changes
LGTM

2020-09-04 05:18 UTC, merged