Add NCI download DAGs for WOfS and Geomedian summary products
GeoscienceAustralia/dea-airflow pull request #660
Opened 2022-03-02 00:51 UTC by jmettes

Add DAG steps for downloading summary products for WOfS 

* ga_ls_wo_fq_apr_oct_3
* ga_ls_wo_fq_cyear_3
* ga_ls_wo_fq_myear_3
* ga_ls_wo_fq_nov_mar_3

and Geomedian

* ga_ls5t_nbart_gm_cyear_3
* ga_ls7e_nbart_gm_cyear_3
* ga_ls8c_nbart_gm_cyear_3

In order for this to work, I'll need to create the corresponding directories under `/g/data/jw04/ga/`.

There might be some extra work to get indexing to work as well.

2022-03-03 23:50 UTC, omad requested changes
Please add the `trigger_rule` and comment (or improved commentary) back in, otherwise looks great.

2022-03-03 23:50 UTC, omad commented on dags/collection3/nci_c3_download_derivs.py
> -        # Attempt to index downloaded datasets, even if there were some failures in the download
This `trigger_rule` and comment are important. (and if it's not clear we should improve it).

We've had trouble with data being downloaded but not indexed, when s5cmd only partially completes. (eg. downloads 10 of 15 datasets). The Airflow task is marked as *failed*, and without this `trigger_rule` change the indexing job doesn't run.

If the download task runs a second time, it doesn't download the data that's already been downloaded, and so aren't included in the log file that we index from.

2022-03-03 23:50 UTC, omad commented on dags/collection3/nci_c3_download_derivs.py
> -        # Run on the Gadi Data Mover node, it's specifically spec'd for data transfers, and
This comment about using a Gadi Data Mover node for the transfers is relevant and should be kept.

2022-03-03 23:50 UTC, omad commented on dags/collection3/nci_c3_download_derivs.py
> -        # There have been random READ failures when performing this download. So retry a few times.
I'm not sure about this comment, maybe it's truth, maybe it's lies...

2022-03-06 23:03 UTC, jmettes commented on dags/collection3/nci_c3_download_derivs.py
> -        # There have been random READ failures when performing this download. So retry a few times.
I'll leave it in for now - seems to at least serve as a warning of potentially being flaky...

2022-03-07 04:22 UTC, emmaai approved these changes
💯

2022-03-07 04:43 UTC, omad approved these changes

2022-03-07 04:44 UTC, merged