Update webapps for ga_s2m_ard_3
GeoscienceAustralia/dea-airflow pull request #955
Opened 2022-11-14 04:17 UTC by jmettes

2022-11-14 04:30 UTC, JM-GA reviewed
Should the ids be: ga_s2am_ard_3', 'ga_s2bm_ard_3'
rather than ga_s2_s2am_ard_3 and ga_s2_s2bm_ard_3
or does explorer use different product id?

2022-11-14 04:58 UTC, jmettes commented
> Should the ids be: ga_s2am_ard_3', 'ga_s2bm_ard_3' rather than ga_s2_s2am_ard_3 and ga_s2_s2bm_ard_3 or does explorer use different product id?

Woops my bad - good catch! Fixed.

2022-11-16 05:51 UTC, pindge requested changes

2022-11-16 05:51 UTC, pindge commented on dags/webapp_update/update_list.py
> +    "ga_s2bm_ard_3",
put the combined layer name instead, it will flow down

2022-11-17 05:31 UTC, pindge approved these changes

2022-11-17 22:37 UTC, merged